### ISSUE TITLE
New test issue

### ISSUE THREAD

**Issue by jpclaro** [jpclaro/smartsite#1]
aergdfgadfg

**Comment by jpclaro** [comment]
comment

**Comment by jpclaro** [comment]
```yaml
esp32_touch:
  setup_mode: false
  id: touch_id
  sleep_duration: 400ms
  #measurement_duration: 1ms
  iir_filter: 10ms
  high_voltage_reference: 2.4V

binary_sensor:
  - platform: esp32_touch
    name: "below 100"
    id: "capacity_100"
    pin: GPIO15
    threshold: 650
```
